# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %>
  domain_name: example.com
  secret_key_base: abafb9b5b9e6642d95699fa3659ef138e232e54927d57f00af411a1ac78b9c5b0a8a6b9b798a02bc9d04a23b49989736ab5f96c11cc0e602e3b8bef40dd99700

test:
  secret_key_base: 3759cc865f4aca8f21c84991aee2f561d93c8e42ca609e7423b65d20f518853198d8700b3185b1295ec6676404b84760ff1d3b0066a49beb18984e0f70d8f55b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
